# Generated by Django 4.0.5 on 2022-06-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_id_user_perevaluser_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevalimages',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
