# Generated by Django 4.0.5 on 2022-06-26 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_perevalimages_date_added'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivitiesTypes',
        ),
    ]
